[package]
name = "bitset"
version = "0.1.0"
edition = "2021"


[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
path = "src/bench.rs"
harness = false
[features]
incomplete_set = []
